### ISSUE TITLE
ignore .git by default

### ISSUE THREAD

**Issue by zachvalenta** [bootandy/dust#101]
Thinking that this could be configurable but IMO makes sense to ignore `.git` by default.

**Comment by bootandy** [comment]
You are the second person to mention ignoring .git files, so I feel I should listen.

I envisaged people using this to see where their disk is being used up. Clearly people have other users, (which is great), but I want to understand why you want to ignore .git files.

**Comment by thisguychris** [comment]
hey @bootandy 👋 let do another +1 on the idea. Would love to have a configurable file for ignore. We can take `ripgrep` and `fd` approach where they have a global `~/.ignore` and also respects current `~/.gitignore`

I would love to have an option to ignore hidden files too.

**Comment by bootandy** [comment]
I'll try to get this in but it won't be on by default, you will have to pass a --hide-hidden flag or something.

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/111
