### ISSUE TITLE
add man page

### ISSUE THREAD

**Issue by zachvalenta** [bootandy/dust#102]
There doesn't seem to be a man page.

I've installed on macos via Hombrew:
```sh
$ brew info dust
dust: stable 0.5.2 (bottled), HEAD
```

**Comment by bootandy** [comment]
Do you know how to add one? If so please let me know how. 

Already raised here: https://github.com/bootandy/dust/issues/45

**Comment by zachvalenta** [comment]
My bad! Searched around but missed #45.
