### ISSUE TITLE
Find biggest folders (by number of files)

### ISSUE THREAD

**Issue by nu8** [bootandy/dust#103]
Is it possible?

**Comment by bootandy** [comment]
So find the folder with the most files in?
It's probably possible.

**Comment by nu8** [comment]
So, pretty much same output as what is currently produced. A list of the largest `N` files or folders. But instead of sorting by size of file or folder - sort by number of files in a folder.

My use case was this. I was trying to copy over a folder, but it was going really slow because some subfolder had 30,000 small files - eventually I found that it was Google Chrome cache folder - but would be nice for a faster way to find this stuff

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/109
added with this ^

**Comment by nu8** [comment]
Looks good! I built like this:

~~~
$env:RUSTFLAGS = '-C link-arg=-s'
cargo build --release
~~~

The run one of these:

~~~
dust -f
dust --filecount
~~~

Thank you!
