### ISSUE TITLE
Add flag to limit depth

### ISSUE THREAD

**Issue by bootandy** [bootandy/dust#11]
From Reddit:

Once thing I notice however is that you elected for limiting the number of lines rather then the depth of the tree. It would be a lot more useful to specify the depth of the tree like the way tree -L 3 works.

Not yet sure how this would work. Would "dust -d 2" show:
1) All folders of depth 2 and below
2) Show the biggest 15 but not show any subdirectories that were deeper than 2. 

I imagine the (1) is correct

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/commit/e6c777fb8bfe079b6a517abd4f8a80ff6611e251

**Comment by ryuheechul** [comment]
### A small report
_let me know if you want me to file another issue on this_

`dust -d 2 ~` works but not `dust ~ -d 2` (silently fail?). My `dust` version is `0.6.2` and system is macOS M1.
On the contrast, `du` works either way. Thus I think people (at least me) would expect this would work as well?

**Comment by bootandy** [comment]
That will be an issue with the CLAP command arg parsing library, it might be possible to make it understand this or it might not. I'll look in to the clap usage instructions.
