### ISSUE TITLE
Dust 0.5.3 reports wrong version number

### ISSUE THREAD

**Issue by cdzombak** [bootandy/dust#116]
1. Download `dust` 0.5.3 from https://github.com/bootandy/dust/releases/download/v0.5.3/dust-v0.5.3-x86_64-unknown-linux-musl.tar.gz
2. Run `dust -V` from the downloaded package
3. Observe it reports version 0.5.2

**Comment by bootandy** [comment]
You are correct, I incremented the version number after pushing the tag. Sorry. But apart from the --version showing 0.5.2 it is version 0.5.3
