### ISSUE TITLE
Readme: sort -h can sort human-readable numbers

### ISSUE THREAD

**Issue by Emerentius** [bootandy/dust#12]
The following part in the README.md isn't quite correct

> [du -b] for when you have a bunch and need to sort the output numerically, and you’re obligated to either further pass it into something like awk to turn bytes into the appropriate human-friendly unit like mega or gigabytes, or you just do some rough math in your head and use the ordering to sanity check. 

Given that sort has a `-h` flag for sorting human-readable numbers correctly, that part is a bit misleading.

Edit: I just noticed that sort -h is already given as an alternative at the bottom. Changed comment text.

**Comment by bootandy** [comment]
README updated to make this clearer.
