### ISSUE TITLE
Option to not display total.

### ISSUE THREAD

**Issue by stranger-danger-zamu** [bootandy/dust#123]
I have a directory which in total consumes over 1TB, but the subdirectories don't really go above 60GB a piece. The total bar consumes and crushes the rest of the values and makes it not very useful. The option to not show the total row would be great. 

(Also thank you for the neat tool! I've been using it nearly daily since I've found it.)

**Comment by bootandy** [comment]
That's an interesting edge case. I'll think about this when I next play around with the code.

**Comment by bootandy** [comment]
I'm not keen on doing this. If I added an option to not show the total bar then the other bars would still be just as tiny. If I made the bars scale to only consider those in the output of the tool then I feel I'd be lying to people about all the other directories that weren't quite big enough to be listed.
