### ISSUE TITLE
Support --width flag for non-terminal output

### ISSUE THREAD

**Issue by Nemo157** [bootandy/dust#126]
I want to show `dust` output inside some environments where it is not possible to read the terminal width. The simplest example is if piping the output into a pager like `less`:

![temp](https://user-images.githubusercontent.com/81079/99066952-22983300-25aa-11eb-8486-ba41a1c02f8a.png)

These environments normally have variables available that can be passed into the command, so being able to specify something like `--width=$COLUMNS` would be useful.

**Comment by bootandy** [comment]
yep I'm happy to add this flag.
