### ISSUE TITLE
What do 4 kinds of percentage-bar-characters mean?

### ISSUE THREAD

**Issue by rhdxmr** [bootandy/dust#127]
Hello, I am new to dust.
I am curious about the percentage bar.

There are 4 kinds of characters which displays the percentage bar: ░,  ▒, ▓, █
Which means what?

![dust screenshot](https://user-images.githubusercontent.com/236042/99224246-4fa64900-2829-11eb-83f4-13d26e06df7b.png)

Thanks,

**Comment by bootandy** [comment]
It is visualizing what % of your disk the dir is using. 

TensorRT is 65% of your disk. But if you look at plugin it is 42%. But plugin is inside TensorRT directory. So if you look at the solid bar in plugin you can see it takes up about 2/3rds of the space of the previous bar (marked by light boxes) so its about 2/3rds of the TensorRT directory.

If this makes sense to you feel free to rewrite it in a way that makes sense to you and I'll add it to the README.
