### ISSUE TITLE
when I am using tmux for splitting the terminal, dust output is weird

### ISSUE THREAD

**Issue by monacv** [bootandy/dust#128]
could you please suggest a fix for $ dust . to have results proportial to size of splitted window in tmux?

![Screenshot from 2020-12-31 15-03-13](https://user-images.githubusercontent.com/76495162/103424331-86d27e80-4b79-11eb-834f-8be78d5fec9f.png)

**Comment by bootandy** [comment]
I didn't know about this, I'll play with tmux and see if I can figure out what is going on

**Comment by bootandy** [comment]
I tried splitting the screen on tmux and dust works correctly on my box.

I'm guessing that dust isn't able to get your screen width.

What happens if you run a simple rust program like this to get the width of your screen? Is the number incorrect?

```

use terminal_size::{terminal_size, Height, Width};

fn get_width_of_terminal()  {
    if let Some((Width(w), Height(_h))) = terminal_size() {
      println!("{:?}", w);
    }
 }
    

```
