### ISSUE TITLE
Suggestion: Package dust for popular Linux distros

### ISSUE THREAD

**Issue by sbrl** [bootandy/dust#129]
Personally, I'm a big Debian-based distro user. Having an apt repository I can install `dust` from would make it much easier to keep up-to-date with less effort. A great tool I've found for making .deb packages (and lots of other packages too) is [`fpm`](https://github.com/jordansissel/fpm).

Other distros might be worth considering too.

**Comment by bootandy** [comment]
I build releases shown here: https://github.com/bootandy/dust/releases

If you want to add the building of other packages I'm happy to include it into the release process.

**Comment by sbrl** [comment]
I see! What I'm trying to get at is that it would be great if the installation of tools like `dust` is as easy as possible, so packaging it and potentially even getting it included in e.g. the default debian/ubuntu repos would seriously increase visibililty and ease of use.

I'd love to do this myself, but unfortunately I don't have any near the amount of time I'd need to do this any time soon.

**Comment by bootandy** [comment]
I wasn't trying to sound unfriendly. I have just struggled to build packages in the past and don't personally enjoy that part of development much.
