### ISSUE TITLE
Autocompletion for fish shell is missing.

### ISSUE THREAD

**Issue by chshbh** [bootandy/dust#134]
Hey!

I do no see an autocompletion feature for the fish shell, I am not sure about the bash/zsh shell. A couple of questions.
+ Is this feature available for other shells?
+ Do you personally not use any tab completion?

Thanks

**Comment by bootandy** [comment]
Personally I tend to use history not tab completion. 

tab completion seems to work on zsh & bash. I haven't used fish but if you can work out how to include it I'll accept a PR.
