### ISSUE TITLE
Malware detection in virustotal (false positive)

### ISSUE THREAD

**Issue by themanifold** [bootandy/dust#135]
I found that virustotal has a false positive detection for the dust.exe binary, from here:

https://github.com/bootandy/dust/releases/download/v0.5.4/dust-v0.5.4-i686-pc-windows-msvc.zip

the sha256 is 5dd87d3d6b9d8b4016e3c36b189234772661e690c21371f1eb8e018f0f0dec2b

The false positive hit is just here: https://www.virustotal.com/gui/file/5dd87d3d6b9d8b4016e3c36b189234772661e690c21371f1eb8e018f0f0dec2b/detection

It is detected by VBA32 as a `BScope.Trojan.Udochka` trojan.

VBA32 is a Belarusian Antivirus product: https://en.wikipedia.org/wiki/Vba32_AntiVirus

I don't know what you want to do about it, but it's worth nothing and maybe seeing if you can stop it from being incorrectly detected.

**Comment by xdevs23** [comment]
Does this happen if you recompile it?

**Comment by themanifold** [comment]
I'm not sure actually, I don't have the tool chain set up. Can you run it
through the CI pipeline in GitHub again?

**Comment by xdevs23** [comment]
I'm not part of this project but I can actually just try this myself.

I ran my locally compiled file through VirtusTotal and it shows no finds: https://www.virustotal.com/gui/file/ae67bac1f16533fc09c724f5570b72141824e7fe1efc98902092f8b5babdc024/detection

So my guess is that it's really just a coincidence.
