### ISSUE TITLE
Multiple arguments should be unified under 1 scale

### ISSUE THREAD

**Issue by KSXGitHub** [bootandy/dust#136]
I often use `dust <file1> <file2> <file3>` to compare their sizes. Unfortunately, their visual bars all have the same length despite their different sizes.

### Command

```sh
dust /bin/ls /bin/docker
```

### Expected behaviour

```
 140K   ┌── ls       │                                                  █ │   0%
  51M   ├── docker   │███████████████████████████████████████████████████ │ 100%
  51M ┌─┴ ls + docker│███████████████████████████████████████████████████ │ 100%
```

### Actual behaviour

```
 140K ┌── ls    │████████████████████████████████████████████████████████ │ 100%
  51M ┌── docker│████████████████████████████████████████████████████████ │ 100%
```

**Comment by xdevs23** [comment]
Just my two cents: Perhaps adding a command line argument like `--compare` to enable this behavior could be better than changing the default behavior for everyone.

**Comment by KSXGitHub** [comment]
@xdevs23 I find no use case where bars having the same length despite their different sizes make sense. Not to mention, if a user really wish the old behaviour for some inexplicable reason, they can always call `dust` multiple times (i.e. `dust foo && dust bar` instead of `dust foo bar`).

**Comment by xdevs23** [comment]
@KSXGitHub that's a good point, I agree.

**Comment by bootandy** [comment]
I've wondered about this myself. 

I did design it that way on purpose originally but in hindsight I think that might have been a mistake. 

It's a breaking change but I think it's a reasonable request. I'll try and include it in the next major version release.

**Comment by bootandy** [comment]
behaviour changed in v0.6.0
