### ISSUE TITLE
cannot install with cargo on centos 7

### ISSUE THREAD

**Issue by monacv** [bootandy/dust#140]
[jalal@goku ~]$ cargo install du-dust
    Updating crates.io index
  Installing du-dust v0.5.4
error: failed to compile `du-dust v0.5.4`, intermediate artifacts can be found at `/tmp/cargo-installkEkAsJ`

Caused by:
  failed to parse lock file at: /home/grad3/jalal/.cargo/registry/src/github.com-1ecc6299db9ec823/du-dust-0.5.4/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`

**Comment by bootandy** [comment]
duplicate: https://github.com/bootandy/dust/issues/142
