### ISSUE TITLE
`-L` / `--dereference` to follow symlinks

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [bootandy/dust#144]
`du` has the `-L` or `--dereference` flag to follow symlinks to files and directories and include their actual size.

It would be great if `dust` could also support this.

So instead of reporting `0B` per symlink, with `-L` it would report the file size, or for directories the total size of files in that directory.

**Comment by bootandy** [comment]
I deliberately didn't do that. I think that would be weird from a hierarchy point of view.  The link isn't 'in' the directory so if you delete it you won't free up the space associated with it. Also how would the sum total space work - would that include the directories inside a sym link, what if it was recursive?
