### ISSUE TITLE
no output on Windows

### ISSUE THREAD

**Issue by thorstenkampe** [bootandy/dust#153]
The new version 0.6.0 shows no output on Windows while the previous one (0.5.4) does.

**Comment by bootandy** [comment]
ok, lets work on this.

Which version of windows are you using? 
Can you try different directories / Does it only happen with the root directory or networked folders? 
Is there a problem with the permissions on the directory?

**Comment by thorstenkampe** [comment]
I'm running Windows 10. I'll try a different root - outside my Cygwin home directory - tomorrow. The computer in question is part of an Active Directory domain. On my home machine the issue does not occur.

**Comment by jocwurs** [comment]
On Windows dust only counts directories without the Archive attribute.
After running "$attrib /s /d -a *" dust shows all directories.

**Comment by 89z** [comment]
https://github.com/bootandy/dust/issues/212

**Comment by 89z** [comment]
I found an alternative that works:

https://github.com/dundee/gdu

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/releases/tag/v0.8.1-alpha.2

I don't know what the root cause of this but if it is because of the archive Attribute then I removed it with this alpha release. Can a windows user who is seeing this issue try the above alpha2 release and tell me if it fixes the problem? If it does I'll merge it into master. 

Thanks,

**Comment by thorstenkampe** [comment]
No change with `Dust 0.8.1-alpha.2`

**Comment by nico-abram** [comment]
Sent a pull request that seems to fix it in https://github.com/bootandy/dust/pull/218

**Comment by mrbrianevans** [comment]
I am on version 0.8.0 and also getting this error. No output on windows 10.

Example:
```
PS C:\Users\brian\Downloads> dust
PS C:\Users\brian\Downloads>
```
I can assure you that there are plenty of files in my downloads folder, but running the command doesn't print any output. It takes a long to time to run, and CPU is at 100% usage, so its definitely doing something, just not outputing results.


It does seem to work if I run dust on a specific file, such as this:
```
C:\Users\brian\Downloads>dust ideaIU-2019.2.3.exe
Did not have permissions for all directories
 673M ┌── ideaIU-2019.2.3.exe│█████████████████████████████████████████████████████████████████████████████████████████████████████████████████ │ 100%
```

but doesn't work if I run it on a folder/directory.

I am not (knowingly) using archive or network storage. This is just the default regular windows downloads folder.

If #218 fixed this, how can I install it using Cargo? I tried `cargo install du-dust` which installed `du-dust v0.8.0`.
