### ISSUE TITLE
Size of symlinked files rather than size of symlink

### ISSUE THREAD

**Issue by wdecoster** [bootandy/dust#158]
Hi,

Great tool! I found this on https://github.com/ibraheemdev/modern-unix and want to use it on my system.

I am not sure if this is related to #157, but I noticed that dust also counts the file size of the file to which a symlink is pointing, rather than the size of the symlink.
For a directory with symlinks to pretty large files on another filesystem `dust` reports 22T, while `du` just returns 46M.
If I am looking in my home directory for things that use disk space I am not so much concerned about things that actually live on the huge storage server.

Is there already a switch to turn this off? Or is this the intended behavior?

Thanks,
Wouter

**Comment by bootandy** [comment]
Thanks, 

Are the links soft links or hard links? 

If they are soft links I think that is a bug, I did a large refactor recently and if you run dust on a directory tree with soft links pointing to outside that directory tree then it takes the size of the file instead of the size of the symlink.

**Comment by wdecoster** [comment]
Those are soft links. So yes, the soft links point to another file system and thus outside the directory tree.

**Comment by AckslD** [comment]
Is it possible to tell it to report the size of the symlink with some argument?

**Comment by bootandy** [comment]
This is a bug. I will fix it.

**Comment by bootandy** [comment]
fixed in v0.6.1
