### ISSUE TITLE
Can I do the interactive mode navigation?

### ISSUE THREAD

**Issue by chenrui333** [bootandy/dust#159]
First, thanks for creating this valuable tool. I wonder if I can do interactive explorations of the source code. Thanks!

**Comment by bootandy** [comment]
I'm not sure what you mean. 

You are welcome to look at the source code and you are welcome to make a video or livestream it.

**Comment by bootandy** [comment]
Do you mean add an interactive mode like NCDU has? I wondered about doing this but I'm not sure about it. I feel ncdu has that base well covered.

You are welcome to try it, we can add it behind an '--interactive' flag or something similar.

**Comment by bootandy** [comment]
no updates on this issue, closing.
