### ISSUE TITLE
Percentage bar scaling suboptimal when there are lots of relatively small subdirectories

### ISSUE THREAD

**Issue by taladar** [bootandy/dust#169]
If even the largest subdirectories are just a relatively small percentage (e.g. < 5%) of the current directory the display of the current directory 100% bar completely hides the detail in the rest of the graph. In this case it might be useful to have an option to skip the display of the 100% bar and scale everything to the next largest bar.

**Comment by bootandy** [comment]
while i sympathise with this I can't imagine a nice way to display that. I think just cutting out the first bar would screw up the placement of the others.
