### ISSUE TITLE
Match sub-directories or allow globs/regexs with `--ignore-directory`

### ISSUE THREAD

**Issue by andreavaccari** [bootandy/dust#173]
Hi, thank you for your work on `dust`. This is a suggestion for improvement. The `--ignore-directory` flag currently does not match subdirectories. This would be very helpful, for example, to analyze a directory containing many repos, each containing directories to ignore: `dust -f -X .git -X node_modules ~/dir-with-many-repos`.

Possible improvements are:
- Matching the specified names against a candidate's name instead of its relative path.
- Allowing to specify patterns with globs (`**/node_modules`) or regexs (`.*/node_modules$`).

The latter is more complex but more flexible, and would make it so only one flag could/should be specified.

Unfortunately I'm not familiar with Rust. I hope you'll consider implementing this in the future. Thank you!

**Comment by andreavaccari** [comment]
Yes, your example matches my suggestion.

At the moment, to exclude the two directories in your example you would have to run:

`dust -X a/node_modules -X other_dir/sub_dir/node_modules ~/dir-with-many-repos`

If you had several directories, you'd have to use `find -exec` or `xargs`. Being able to do this with `dust` alone would be great!

**Comment by bootandy** [comment]
I have just (accidentally) created this feature with this commit https://github.com/bootandy/dust/pull/174/commits/1d1bada2e402714b2c77900496616f4bca49dd5f

It will mimic the `grep -v regex` behaviour. Which will allow you to do `dust -v node_modules`

The commit isn't released yet.

**Comment by bootandy** [comment]
Fixed with version 0.7

**Comment by andreavaccari** [comment]
Hi @bootandy, I wanted to confirm that the `-v` option helped tremendously with my use case.

Could you clarify the following when you have a moment?

- With `-e` and `-v`, is it possible to match a pattern against a candidate's relative path instead of just its filename?
- With `-e`, it's possible to declare multiple patterns. With `-v`, only the first pattern takes effect. Is this intended?

Thank you!
