### ISSUE TITLE
New release no packages!

### ISSUE THREAD

**Issue by bootandy** [bootandy/dust#178]
Hey @ethanhs I pushed a new release of dust today and the packages didn't build. 
I may have made a mistake somewhere but I think the only changes to CICD came from you - and my current instinct is to revert these commits: - can you see any problems that might cause the package to not build?

https://github.com/bootandy/dust/commit/f51e9dd222205f46a760468f742f14f593d77c94
https://github.com/bootandy/dust/commit/c25f7d342cb016b4e7c485315035559cef3ab04b

thanks,

**Comment by bootandy** [comment]
My mistake apologies,

https://github.com/bootandy/dust/compare/reverts2?expand=1

**Comment by ethanhs** [comment]
No problem, reasonable to assume the last change broke things! I also should note that I only upload the .debs to actions output, so you may want to also add to the files list a glob for .deb files (maybe based on https://github.com/bootandy/dust/blob/master/.github/workflows/CICD.yml#L235) for the release step.

**Comment by bootandy** [comment]
@ethanhs 

I have to be honest, I don't have a good grasp of the build file as someone else made it. 

I thought this change (or the proceeding one) would include the deb files but it doesn't seem to, can you explain what I did wrong, thanks.

https://github.com/bootandy/dust/commit/4e3c50177bfd31ab8146b43adda6ae5dce332cef

**Comment by ethanhs** [comment]
`cargo-deb` puts the output in `target/<target triple>/debian/<some long thing>.deb` so I think you can change `target/${{ matrix.job.target }}/debian` to `target/${{ matrix.job.target }}/debian/*.deb`

**Comment by bootandy** [comment]
Got it - thank you. 
https://github.com/bootandy/dust/releases
They'll be in the next proper release.

**Comment by ethanhs** [comment]
Great! Glad things are working :)
