### ISSUE TITLE
Allow decimal sizes (1k = 1000 instead of 1024)

### ISSUE THREAD

**Issue by eugenesvk** [bootandy/dust#182]
Currently all sizes are displayed with a **binary** prefix (1k=1024=2¹⁰)
Please add an option to use **decimal** prefixes (1k=1000=10³)
Thanks!

**Comment by bootandy** [comment]
That doesn't strike me as that useful, what's your usecase?

However du does allow something similar with the -B blocksize, so I'm happy to leave this open if you want to work on it.
