### ISSUE TITLE
Hide decimals when there are only zeroes instead of approximately zero

### ISSUE THREAD

**Issue by eugenesvk** [bootandy/dust#183]
For example, I have two files with the sizes of 1 byte and 1024 bytes, dust would provide the following output:
```
  1B   ┌── 1b      
1.0K   ├── 1024b   
```
However, since `1024` is precisely `1KB`, abbreviating it to `1.0K` is misleading as I might think that in reality it's `1.04K` shortened to the first decimal, so I'd prefer to see the following output, which is also cleaner

```
  1B   ┌── 1b      
1  K   ├── 1024b   
```

**Comment by bootandy** [comment]
I'm afraid I really don't like that syntax, so that's a no from me.
