### ISSUE TITLE
Allow custom prefixes

### ISSUE THREAD

**Issue by eugenesvk** [bootandy/dust#184]
It'd be great if we could set an environment variable/config option that would replace the default prefixes

For example, I have 4 files of 1b, 1k, 1m and 2m sizes, the default `dust -b -s` view is:
```
   1B   ┌── 1b
 1.0K   ├── 1024b
1000K   ├── 1048576b
 2.0M   ├── 2097152b
```
I'd prefer it to look like:
```
   1    ┌── 1b
 1.0k   ├── 1024b
1000k   ├── 1048576b
 2.0M   ├── 2097152b
```
this way it's easier to differentiate between bytes and kilobytes as well as between kilo and mega (since `M` is capitalized vs `k`)

**Comment by bootandy** [comment]
Sorry, I'm not convinced this is worth doing. thanks for you thoughts though.
