### ISSUE TITLE
test_show_files_by_regex_match_multiple fails...

### ISSUE THREAD

**Issue by s0nspark** [bootandy/dust#194]
I am seeing this test fail when trying to build from the d983175 commit on Arch Linux using the AUR PKGBUILD.

Here is the complete output using RUST_BACKTRACE=full: 

`
==> Making package: dust-git 0.6.2.r26.gd983175-1 (Wed 27 Oct 2021 09:30:47 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating dust git repo...
Fetching origin
==> Validating source files with sha256sums...
    dust ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of dust git repo...
Cloning into 'dust'...
done.
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
   Compiling libc v0.2.101
   Compiling autocfg v1.0.1
   Compiling lazy_static v1.4.0
   Compiling crossbeam-utils v0.8.5
   Compiling cfg-if v1.0.0
   Compiling crossbeam-epoch v0.9.5
   Compiling memchr v2.4.1
   Compiling scopeguard v1.1.0
   Compiling rayon-core v1.9.1
   Compiling unicode-width v0.1.8
   Compiling regex-syntax v0.6.25
   Compiling bitflags v1.3.2
   Compiling ansi_term v0.12.1
   Compiling either v1.6.1
   Compiling ansi_term v0.11.0
   Compiling strsim v0.8.0
   Compiling vec_map v0.8.2
   Compiling thousands v0.2.0
   Compiling lscolors v0.7.1
   Compiling memoffset v0.6.4
   Compiling rayon v1.5.1
   Compiling crossbeam-channel v0.5.1
   Compiling aho-corasick v0.7.18
   Compiling term_size v0.3.2
   Compiling num_cpus v1.13.0
   Compiling atty v0.2.14
   Compiling terminal_size v0.1.17
   Compiling textwrap v0.11.0
   Compiling clap v2.33.3
   Compiling crossbeam-deque v0.8.1
   Compiling regex v1.5.4
   Compiling stfu8 v0.2.4
   Compiling du-dust v0.7.5 (/home/tim/.cache/paru/clone/dust-git/src/dust)
    Finished release [optimized] target(s) in 27.15s
==> Starting check()...
   Compiling libc v0.2.101
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.0.1
   Compiling lazy_static v1.4.0
   Compiling crossbeam-utils v0.8.5
   Compiling memchr v2.4.1
   Compiling crossbeam-epoch v0.9.5
   Compiling rayon-core v1.9.1
   Compiling either v1.6.1
   Compiling scopeguard v1.1.0
   Compiling unicode-width v0.1.8
   Compiling doc-comment v0.3.3
   Compiling ppv-lite86 v0.2.10
   Compiling predicates-core v1.0.2
   Compiling regex-syntax v0.6.25
   Compiling bitflags v1.3.2
   Compiling difflib v0.4.0
   Compiling ansi_term v0.12.1
   Compiling regex-automata v0.1.10
   Compiling ansi_term v0.11.0
   Compiling treeline v0.1.0
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling thousands v0.2.0
   Compiling remove_dir_all v0.5.3
   Compiling itertools v0.10.1
   Compiling lscolors v0.7.1
   Compiling memoffset v0.6.4
   Compiling rayon v1.5.1
   Compiling predicates-tree v1.0.3
   Compiling crossbeam-channel v0.5.1
   Compiling aho-corasick v0.7.18
   Compiling bstr v0.2.16
   Compiling crossbeam-deque v0.8.1
   Compiling getrandom v0.2.3
   Compiling num_cpus v1.13.0
   Compiling term_size v0.3.2
   Compiling atty v0.2.14
   Compiling wait-timeout v0.2.0
   Compiling terminal_size v0.1.17
   Compiling rand_core v0.6.3
   Compiling textwrap v0.11.0
   Compiling clap v2.33.3
   Compiling rand_chacha v0.3.1
   Compiling predicates v2.0.2
   Compiling regex v1.5.4
   Compiling rand v0.8.4
   Compiling assert_cmd v1.0.8
   Compiling tempfile v3.2.0
   Compiling stfu8 v0.2.4
   Compiling du-dust v0.7.5 (/home/tim/.cache/paru/clone/dust-git/src/dust)
    Finished test [unoptimized + debuginfo] target(s) in 20.07s
     Running unittests (target/debug/deps/dust-eec1f7a393281571)

running 13 tests
test dir_walker::tests::test_should_ignore_file ... ok
test dir_walker::tests::test_should_not_ignore_files_if_using_apparent_size ... ok
test utils::tests::test_is_a_parent_of ... ok
test display::tests::test_human_readable_number ... ok
test utils::tests::test_simplify_dir_duplicates ... ok
test utils::tests::test_simplify_dir_rm_subdir ... ok
test utils::tests::test_is_a_parent_of_root ... ok
test utils::tests::test_simplify_dir_substring_names ... ok
test utils::tests::test_simplify_dir_rm_subdir_and_not_substrings ... ok
test utils::tests::test_simplify_dir_dots ... ok
test display::tests::test_format_str ... ok
test utils::tests::test_simplify_dir ... ok
test display::tests::test_format_str_long_name ... ok

test result: ok. 13 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/tests.rs (target/debug/deps/integration-1282f6d1186949dd)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/test_exact_output.rs (target/debug/deps/test_exact_output-0d8e99f88c9133d6)

running 9 tests
test tests_symlinks::test_recursive_sym_link ... ok
test tests_symlinks::test_hard_sym_link ... ok
test test_apparent_size ... ok
test test_substring_of_names_and_long_names ... ok
test test_unicode_directories ... ok
test tests_symlinks::test_soft_sym_link ... ok
test test_main_basic ... ok
test test_main_multi_arg ... ok
test test_main_long_paths ... ok

test result: ok. 9 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

     Running tests/test_flags.rs (target/debug/deps/test_flags-affc89d6ca76d725)

running 15 tests
test test_basic_output ... ok
test test_d_flag_works ... ok
test test_ignore_dir ... ok
test test_d_flag_works_and_still_recurses_down ... ok
test test_output_no_bars_means_no_excess_spaces ... ok
test test_reverse_flag ... ok
test test_show_files_by_regex_match_lots ... ok
test test_show_files_by_invert_regex_match_multiple ... ok
test test_number_of_files ... ok
test test_hidden_flag ... ok
test test_with_bad_param ... ok
test test_show_files_by_regex_match_nothing ... ok
test test_show_files_by_type ... ok
test test_show_files_by_invert_regex ... ok
test test_show_files_by_regex_match_multiple ... FAILED

failures:

---- test_show_files_by_regex_match_multiple stdout ----
thread 'test_show_files_by_regex_match_multiple' panicked at 'assertion failed: output.contains(\"test_dir_unicode\")', tests/test_flags.rs:146:5
stack backtrace:
   0:     0x562702c90940 - std::backtrace_rs::backtrace::libunwind::trace::ha6c3510fe821ece8
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x562702c90940 - std::backtrace_rs::backtrace::trace_unsynchronized::h5d5e87c6b99f4921
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562702c90940 - std::sys_common::backtrace::_print_fmt::hff4be27ec1976221
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x562702c90940 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h117c3474e52d75fd
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x562702cb4c4c - core::fmt::write::h8e79414eb36647e2
                               at /build/rust/src/rustc-1.56.0-src/library/core/src/fmt/mod.rs:1150:17
   5:     0x562702c8ccd5 - std::io::Write::write_fmt::he58d8b04c14aa828
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/io/mod.rs:1667:15
   6:     0x562702c9261b - std::sys_common::backtrace::_print::h2f0b89d92ed2f258
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x562702c9261b - std::sys_common::backtrace::print::ha440767f4a888cb0
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x562702c9261b - std::panicking::default_hook::{{closure}}::hb2b320b52639dd19
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panicking.rs:210:50
   9:     0x562702c921c8 - std::panicking::default_hook::h9e49f1f8456637e8
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panicking.rs:224:9
  10:     0x562702c92cf4 - std::panicking::rust_panic_with_hook::hcf89422866cc5cba
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panicking.rs:624:17
  11:     0x562702c92792 - std::panicking::begin_panic_handler::{{closure}}::h317ad046b7c4bad7
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panicking.rs:519:13
  12:     0x562702c90e04 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e316d1568d54ecf
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x562702c92729 - rust_begin_unwind
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panicking.rs:517:5
  14:     0x562702c09421 - core::panicking::panic_fmt::h1e504aaf1a9d1c8d
                               at /build/rust/src/rustc-1.56.0-src/library/core/src/panicking.rs:101:14
  15:     0x562702c0936d - core::panicking::panic::h637da157b755664e
                               at /build/rust/src/rustc-1.56.0-src/library/core/src/panicking.rs:50:5
  16:     0x562702c12643 - test_flags::test_show_files_by_regex_match_multiple::h727b3e4c335077c3
                               at /home/tim/.cache/paru/clone/dust-git/src/dust/tests/test_flags.rs:146:5
  17:     0x562702c0c6ba - test_flags::test_show_files_by_regex_match_multiple::{{closure}}::h18331af87dfda762
                               at /home/tim/.cache/paru/clone/dust-git/src/dust/tests/test_flags.rs:134:1
  18:     0x562702c0d33e - core::ops::function::FnOnce::call_once::hfe52f8c1383003d1
                               at /build/rust/src/rustc-1.56.0-src/library/core/src/ops/function.rs:227:5
  19:     0x562702c47113 - core::ops::function::FnOnce::call_once::hf50285b7b4ffa5a4
                               at /build/rust/src/rustc-1.56.0-src/library/core/src/ops/function.rs:227:5
  20:     0x562702c47113 - test::__rust_begin_short_backtrace::h5edb275f20206441
                               at /build/rust/src/rustc-1.56.0-src/library/test/src/lib.rs:578:5
  21:     0x562702c45bd8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h02080db1c828d340
                               at /build/rust/src/rustc-1.56.0-src/library/alloc/src/boxed.rs:1636:9
  22:     0x562702c45bd8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb0ed4e26170d63ae
                               at /build/rust/src/rustc-1.56.0-src/library/core/src/panic/unwind_safe.rs:271:9
  23:     0x562702c45bd8 - std::panicking::try::do_call::h4b76d8c02083e3fe
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panicking.rs:403:40
  24:     0x562702c45bd8 - std::panicking::try::h3cce50ce742a70c8
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panicking.rs:367:19
  25:     0x562702c45bd8 - std::panic::catch_unwind::hb29f2734e9f70303
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panic.rs:129:14
  26:     0x562702c45bd8 - test::run_test_in_process::hb282610b2775974a
                               at /build/rust/src/rustc-1.56.0-src/library/test/src/lib.rs:601:18
  27:     0x562702c45bd8 - test::run_test::run_test_inner::{{closure}}::h891bb263c431e1b2
                               at /build/rust/src/rustc-1.56.0-src/library/test/src/lib.rs:493:39
  28:     0x562702c13392 - test::run_test::run_test_inner::{{closure}}::h796a17c2b36ad96f
                               at /build/rust/src/rustc-1.56.0-src/library/test/src/lib.rs:520:37
  29:     0x562702c13392 - std::sys_common::backtrace::__rust_begin_short_backtrace::h114919d11c895dc1
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/sys_common/backtrace.rs:125:18
  30:     0x562702c17db8 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::he69fad208e8798fc
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/thread/mod.rs:481:17
  31:     0x562702c17db8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he24a1ccd99c11deb
                               at /build/rust/src/rustc-1.56.0-src/library/core/src/panic/unwind_safe.rs:271:9
  32:     0x562702c17db8 - std::panicking::try::do_call::h7e9f76f916164fdb
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panicking.rs:403:40
  33:     0x562702c17db8 - std::panicking::try::hb39b18bea5f6318e
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panicking.rs:367:19
  34:     0x562702c17db8 - std::panic::catch_unwind::h404937fe646b8938
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/panic.rs:129:14
  35:     0x562702c17db8 - std::thread::Builder::spawn_unchecked::{{closure}}::h1b17641857279170
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/thread/mod.rs:480:30
  36:     0x562702c17db8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h70f40c7afef97115
                               at /build/rust/src/rustc-1.56.0-src/library/core/src/ops/function.rs:227:5
  37:     0x562702c97fb3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfc53ec28d8470341
                               at /build/rust/src/rustc-1.56.0-src/library/alloc/src/boxed.rs:1636:9
  38:     0x562702c97fb3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha1ca89319f3375b5
                               at /build/rust/src/rustc-1.56.0-src/library/alloc/src/boxed.rs:1636:9
  39:     0x562702c97fb3 - std::sys::unix::thread::Thread::new::thread_start::ha2d3919bfd51eaa4
                               at /build/rust/src/rustc-1.56.0-src/library/std/src/sys/unix/thread.rs:106:17
  40:     0x7f06a2f67259 - start_thread
  41:     0x7f06a2d455e3 - __GI___clone
  42:                0x0 - <unknown>

failures:
    test_show_files_by_regex_match_multiple

test result: FAILED. 14 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

error: test failed, to rerun pass '--test test_flags'
==> ERROR: A failure occurred in check().
    Aborting...

`

**Comment by bootandy** [comment]
Noted, I'm seeing that test fail on Mac too and I haven't yet figured out why, I'll do some digging.

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/196
This is 'fixed' or hidden on mac by this PR. 

Curious to know if this fixes the issue, although please note I've really hidden it rather than fixed it, (I don't have a mac so its tricky for me to track down)
