### ISSUE TITLE
arm build "bash: ./dust: cannot execute binary file: Exec format error" but can build from source

### ISSUE THREAD

**Issue by bbugh** [bootandy/dust#200]
Hi! 👋🏻 Thank you for making dust, it's awesome!

debian-11.1.0-arm64 virtualized in an Apple M1:

```
$ wget https://github.com/bootandy/dust/releases/download/v0.7.5/dust-v0.7.5-arm-unknown-linux-gnueabihf.tar.gz
$ tar vzxf dust-v0.7.5-arm-unknown-linux-gnueabihf.tar.gz
$ cd dust-v0.7.5-arm-unknown-linux-gnueabihf
$ chmod +x dust

$ ./dust
zsh: exec format error: ./dust

$ bash
$ ./dust
bash: ./dust: cannot execute binary file: Exec format error
```

However, building it from source works:

```
$ docker run --rm -v "$PWD":/usr/src/dust -w /usr/src/dust rust:latest cargo build --release
   ... 
   Compiling du-dust v0.7.5 (/opt/src)
    Finished release [optimized] target(s) in 1m 41s
$ ./target/release/dust
  ...
  49M       ├─┴ deps                                    │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█████████████████████████████ │  60%
  82M     ┌─┴ release                                   │████████████████████████████████████████████████ │ 100%
  82M   ┌─┴ target                                      │████████████████████████████████████████████████ │ 100%
  83M ┌─┴ .                                             │████████████████████████████████████████████████ │ 100%
```

**Comment by anirvan-majumdar** [comment]
Hi — we are trying to get Dust installed on an AWS Graviton (Aarch64) instance and facing a similar issue:
```
bash: ./dust: cannot execute binary file: Exec format error
```

You seem to have built dust from source using `docker`, but is there a way to build the binary from source natively on the instance?

**Comment by bootandy** [comment]
Hi, 

Sorry to hear that. 

This might be a silly suggestion but do any of the other releases work? 

Should we be building a separate release for the M1 processor ? 

I'm afraid I don't know much about creating the releases but I'm happy to help if I can.

**Comment by bbugh** [comment]
Hey @bootandy, thanks for the reply! Nothing special is needed for the M1, it's just an arm64. The executable also doesn't run on a Rasperry Pi, which is also arm64. If you could also output an arm64 build, that would solve it. 

I can check later to see if any old versions ran, but unless they were built for arm64 they most likely won't.

**Comment by bbugh** [comment]
This came up on the sidebar of dev.to and it seems like it might be useful! https://dev.to/marcoieni/rust-makes-cross-compilation-child-s-play-4e4g

**Comment by anirvan-majumdar** [comment]
Worked like a charm @bbugh! 
Installed `cargo` on the Ubuntu instance and ran the command you'd suggested.

**Comment by bootandy** [comment]
Thanks for the info. I'll add an arm64 build when I next fiddle round with the releases 

(I confess I don't much like touching the release scripts!).

**Comment by bootandy** [comment]
I'm not sure I can help anymore on this. 

If someone wants to add a new release to dust that would be welcome, the file is here:
https://github.com/bootandy/dust/blob/master/.github/workflows/CICD.yml

(I don't have an arm system and have not had much luck including a new arm64 build).

**Comment by adamcstephens** [comment]
Confirmed v0.8.1-alpha.2 musl and gnu binaries both work on a raspberry pi running Ubuntu aarch64
