### ISSUE TITLE
Issues with number-of-lines

### ISSUE THREAD

**Issue by 89z** [bootandy/dust#201]
I am confused by this:

https://github.com/bootandy/dust/blob/f70830519044d160d8372fbf46de0e4c3a40d1a6/src/main.rs#L120-L125

What does this mean:

~~~
This is Height, (but h is help)
~~~

The flag is `n`, so what does `h` have to do with anything? Also on Windows, the default height is wrong. Dust thinks my terminal height is 34, when it is actually 42 or more.

**Comment by bootandy** [comment]
I wanted to use the flag `-h` to indicate height, but `-h` is already used for `help` Hence I used `-n` instead. Reading it again perhaps it is confusing and I should just remove the text in brackets. 

The default height is deliberately not quite the full screen. [I think I do (Full height - 10)] I deliberately don't fill the screen so you can see the top of your previous command,
