### ISSUE TITLE
Request for Pacstall Support

### ISSUE THREAD

**Issue by wizard-28** [bootandy/dust#202]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing [pull request](https://github.com/pacstall/pacstall-programs/pull/555) to add Dust to our repository.

We have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation for Dust for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by bootandy** [comment]
>Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.

I think I would prefer it if you did that. 

>Could you include a section in your documentation showing Pacstall as a valid method of installation for Dust for Debian/Ubuntu users? We could make a pull request for that if you want.

Yes I'd be happy to, probably best if you made a PR for that.

**Comment by wizard-28** [comment]
Closed by #203
