### ISSUE TITLE
Core dump with -w <14

### ISSUE THREAD

**Issue by LoipesMas** [bootandy/dust#204]
```
$ dust -w 0
memory allocation of 18446744073709551553 bytes failed
[1]    4118790 abort (core dumped)  dust -w 0
```
Probably because of underflow [here](https://github.com/bootandy/dust/blob/6a34b52d154ff18d21f2ea17314ec6a79864d465/src/display.rs#L132).

**Comment by bootandy** [comment]
good spot

**Comment by bootandy** [comment]
fixed in code, will be fixed on next release.
