### ISSUE TITLE
Configurable file size threshold

### ISSUE THREAD

**Issue by AgathaSorceress** [bootandy/dust#209]
Is there a way to filter out all files/directories below some space usage% (eg. anything smaller than 5%) or some size threshold (eg. <10Mb)? I looked through the documentation and existing issues and couldn't find anything.
I think this feature would be nice to have, if it's not already there!

**Comment by bootandy** [comment]
No I'm afraid no, I considered a space usage limit but I felt it was covered by using '-n' to specify the number of lines you wanted output

**Comment by bootandy** [comment]
Similar request:
https://github.com/bootandy/dust/issues/231

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/252
