### ISSUE TITLE
Package in conda-forge

### ISSUE THREAD

**Issue by peterjc** [bootandy/dust#211]
I've not got any direct experience with compiling rust code, so trying this myself is a little daunting, but having tried dust via https://twitter.com/github/status/1491102284666884109 it would be nice to have it just one line away for installation via my preferred system: conda.

Specifically, it would be great to have Linux, macOS and Windows packages done so ``conda install dust`` would just work - and the easiest way to do that, is package it via conda-forge.

We would start by writing a conda recipe and submitting it via a pull request to https://github.com/conda-forge/staged-recipes - and it turns out there is a stalled work in progress at https://github.com/conda-forge/staged-recipes/pull/15655 where the dust team may be able to help?

**Comment by bootandy** [comment]
I actually don't know who added that package. I'm quite happy for it to be added but I'm afraid I don't know much about conda. 

This link seems to talk about licenses a lot: https://github.com/conda-forge/staged-recipes/pull/15655. 

I have an apache license. How can I help? Am I expected to include all those licenses in the source somewhere?

**Comment by peterjc** [comment]
I was able to get it to build on https://github.com/conda-forge/staged-recipes/pull/18008 (which I am pleasantly surprised by), so I don't think we need your expertise on the build side.

I have not included all the dependency licenses as discussed on https://github.com/conda-forge/staged-recipes/pull/15655 - it looks like there is a process for rust packaging in conda-forge which is still evolving and not yet documented? Again, not obvious that you can help - rather the rust pioneers in conda-forge are needed.

But thank you for the encouragement.
