### ISSUE TITLE
Select a file as baseline rather than total

### ISSUE THREAD

**Issue by Brooooooklyn** [bootandy/dust#216]
For example, I want to compare the compress ratio between different algorithms

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/3468483/160574543-1a733228-5bb5-49a8-b8e3-9e9fbec52550.png">

**Comment by kidonng** [comment]
I would like to see this as well, similar to `du` without `--total`.

**Comment by bootandy** [comment]
Added `--skip-total` flag which will not display the total and will instead base the bar graph on the largest file.
