### ISSUE TITLE
Is this snapcraft official?

### ISSUE THREAD

**Issue by NullVoxPopuli** [bootandy/dust#217]
https://snapcraft.io/dust

just asking as the name of the publisher is different from "bootandy"

publisher has a github tho: @daniejstriata

:shrug: https://github.com/daniejstriata/dust-snap/blob/main/snapcraft.yaml#L33

**Comment by daniejstriata** [comment]
I use the source from the official repo to create the snap package.

**Comment by bootandy** [comment]
That's all good. I need help getting the packages out into all sorts of different locations.  :-)
