### ISSUE TITLE
[WINDOWS]: The argument '--number-of-lines <number_of_lines>' cannot be used with '--depth <depth>'

### ISSUE THREAD

**Issue by yahiaboudah** [bootandy/dust#220]
I want my depth to be 1 so I do: dust -d 1 -r -n Get-File-Count

Get-File-Count is a special powershell function I wrote to get the number of files and dirs in the current directory.

So yeah, it's not working

**Comment by bootandy** [comment]
You can't use both -n and -d. Use one or the other not both.

**Comment by yahiaboudah** [comment]
Can I specify how many directories and files are displayed, say when depth = 5? because it only shows a limited number of dirs, instead of the full length of all available directories and files.

**Comment by bootandy** [comment]
Not currently, I was a bit unsure how it would work if a user provided both depth=5 and number=10. Thinking about it now I don't see why it isn't possible. I'll reopen this issue and take another look when I get time.

**Comment by bootandy** [comment]
also by default using '-d' will show all the directories/file so using '-d 1' means you won't need a -n Get-File-Count
