### ISSUE TITLE
Unable to skip a subfolder using -X 

### ISSUE THREAD

**Issue by Iss-in** [bootandy/dust#222]
say I'm running dust in home directory, and it has structure

folder1
├── folder2
│   └── folder5
├── folder3
└── folder4

then using the -X option, I can only skip the folder1 entirely only,  but If I want dust to ignore the any of other folders specifically, then it doesnt seems to be possible.

I tried , using wildcards or full path to that folder, but didnt wotk

`dust -X folder2`
`dust -X '*folder5'`

can you pls look into it, also it will be really awesome if we can have a global config file which have a section to have a list of foldernames  ( with full paths ) which can be skipped, like

```
[skip_folders]
/home/Isshin/Pictures
/home/Isshin/.local/share/Steam
```

thanks

**Comment by bootandy** [comment]
You can use these:

`dust -v REGEX` `dust -e REGEX`

so you could use this to ignore folders called 'folder'
`dust -v folder`

and this to only include folders called 'folder'
`dust -e folder`

**Comment by bootandy** [comment]
A global config file is something I want to look into.

https://github.com/bootandy/dust/issues/168

**Comment by bootandy** [comment]
-X string matches without regex so you can write:

`dust -X folder1/folder2`

[Use -v if you want regex]

**Comment by Iss-in** [comment]
thanks, guess will wait for the config then

closing this one
