### ISSUE TITLE
How can I ignore file sizes that are smaller than 100k

### ISSUE THREAD

**Issue by avatar-lavventura** [bootandy/dust#231]
I was wondering is it possible to ignore file sizes that are smaller than 100k.

For example I dont want to see following files since they are `4.0K`

```
$ dust
 4.0K    .bashrc
 4.0K    .gitignore
 4.0K    .gitmodules
 4.0K    .pre-commit-config.yaml
 4.0K    .text
 4.0K    README.md
```

**Comment by bootandy** [comment]
There isn't currently an option to do that. I'm not keen on adding it because what about if you had a lot of 4K files that added up to more than 100K should they be included then ? 

Consider `root/subdir1/ ` inside subdir1 we have a lot of 4K files:

```
dust --min-size 5k
200K root
100K  - subdir1
????      - (Why is nothing here the above directory said there was 100K here?)
```

**Comment by avatar-lavventura** [comment]
```bash
dust -H -b -d 1 -n 999999 | tr -d '├──┌─┴' |   \
    sed "/0B/d" | sed "/4.0K/d" | sed "/8.0K/d" | sed "/12K/d" | sed "/16K/d" | sed "/20K/d" | \
    sed "/4.1K/d" | sed "/8.2K/d"
```

**Comment by bootandy** [comment]
i think you are the second person to ask for a min-size option, so I'll think about how that could work.

**Comment by avatar-lavventura** [comment]
Ah sorry for asking options. I just wanted something compact as possible I can manage what I want with additional `sed` :-) Overall `dust` is pretty nice

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/252
