### ISSUE TITLE
Doesn't seem to work on Windows 8.1

### ISSUE THREAD

**Issue by Boscop** [bootandy/dust#24]
It doesn't seem to work on Windows 8.1:
```
> dust
←[38;5;196m 597M←[0m ─┬ .
```

I get the same output, no matter which flags I pass. Any idea why?

**Comment by bootandy** [comment]
I haven't tested in windows8. 
But it looks like it isn't rending the colors correctly

**Comment by orthecreedence** [comment]
Colors work fine on msys, but it only shows the top-level directory and none of the subdirectories (Windows 10 x64, rust stable 1.34.1, gnu).

**Comment by bootandy** [comment]
If anyone runs windows they are welcome to send a pull request to fix it, (and add a test for windows. )

**Comment by bootandy** [comment]
try `dust -c`  for dust in no color mode.

**Comment by bootandy** [comment]
dust now has windows builds running on CI so I am assuming this is fixed unless I hear otherwise.
