### ISSUE TITLE
Symlink support

### ISSUE THREAD

**Issue by dwarfmaster** [bootandy/dust#263]
I'd like to have an equivalent of the `-L` flag of du, that makes it count the size of symlink targets instead of that of symlinks. Since I use nix and git annex, I often encounter directories made only of symlinks, so that feature is very important to me.

**Comment by bootandy** [comment]
The apparent size flag will treat symlinks the same as the actual directories. 

  -s, --apparent-size

**Comment by dwarfmaster** [comment]
Thanks a lot ! I'll close the issue, but maybe the documentation could be updated to make it easier to understand `-s` will do that ?
