### ISSUE TITLE
Feature request: Ignore files by filter file

### ISSUE THREAD

**Issue by windymelt** [bootandy/dust#265]
Hi, I started using this nice tool from today. It seems like very good.

Then I found that there is no option to provide ignore list via a file. (Yes, of course I can ignore file/directory via `-v` option directly one by one)

My use case is:

- I'm building Docker image
- Build is heavy; seems like there is redundant files included inside docker context
- I can remove files/directories from docker context via `.dockerignore` (same format as `.gitignore`)
- So I'm going to find big files not listed in `.dockerignore`

As wrote above, I need feature that ignore files/directories listed in some filter file.

If this tool have this option, that's fantastic.

## Alternative solution

I have workaround

```shell
cat .dockerignore | sed -e 's/^\(.*\)$/-v \1/' | xargs dust
```

**Comment by bootandy** [comment]
there's no option to do that currently, I'll leave this open and I might look at it in the future.

**Comment by Philipp-M** [comment]
Just stumbled over this, having the option to use `.ignore` files (whether that would be `.gitignore` or `.dockerignore`) would be great (e.g. to get the size statistics for a git repo)

Maybe use the `ignore` crate with a `WalkBuilder` for that?

**Comment by bootandy** [comment]
Earlier versions did use WalkBuilder and the ignore crate but they were much slower.

**Comment by bootandy** [comment]
will be added in new version:
https://github.com/bootandy/dust/pull/358
