### ISSUE TITLE
Add option to not limit number of lines in the report

### ISSUE THREAD

**Issue by christosg88** [bootandy/dust#267]
Example usage: `dust --depth 1 --number-of-lines -1`

I want for example to get the size of each direct subdirectory (--depth 1), but not limit the number of lines reported.

Not sure if passing `-1` to the `--number-of-lines` option is the best course, or if adding a new option would be preferable, but it would be a nice functionality we're missing now.

For now I resort to using `--number-of-lines 1000000`

**Comment by bootandy** [comment]
just don't use number-of-lines.

` dust --depth 1 ` should work.
