### ISSUE TITLE
Can dust close multi-threads run?

### ISSUE THREAD

**Issue by karhow** [bootandy/dust#274]
Because my linux machine's data disk is SATA，it will lock when the path have many dirs. Can I run dust use less threads?

**Comment by karhow** [comment]
@rylwin

**Comment by bootandy** [comment]
There used to be that option but it wasn't needed any more. We can bring it back.

**Comment by bootandy** [comment]
Yes you can do this:

 export RAYON_NUM_THREADS=1      
 
 I'll add a note to the source code too.
