### ISSUE TITLE
Support for following symlinks

### ISSUE THREAD

**Issue by teeks99** [bootandy/dust#276]
`dust` would be much nicer with the ability to dereference symlinks on demand, similar to the `-L` argument to `du`.

To elaborate a bit more, this should not be a default. It should only happen when a -L is passed in. If this is the case the program should deal with all the files it finds as if they were in that directory. There may need to be some check to deal with loops in the system though.

The big use case for this is trying to find large files across a system that may span multiple physical drives.

**Comment by bootandy** [comment]
I can look at doing this.

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/288
