### ISSUE TITLE
Bare view and intermediate results?

### ISSUE THREAD

**Issue by brontosaurusrex** [bootandy/dust#278]
1. I'd like to have a single --bare switch that mimics this

    `dust -c -b -d 1 . | sed "s/[^[:alnum:]+-. ]//g"`

2. dust is incredibly fast, but still on huge trees there is some waiting game, it would be helpful if intermediate results are shown (unsorted, maybe with some rules like show only stuff bigger than). [My try](https://raw.githubusercontent.com/brontosaurusrex/bucentaur/master/bin/duh4) at such behavior.

**Comment by bootandy** [comment]
2) - I don't want to show intermediate results. That would result in the screen being constantly redrawn and it would break tools like grep. 
 
 1) I want to do a better job supporting screen-readers see here: https://github.com/bootandy/dust/issues/270 - This might fit well with your 'bare' mode. For now I suggest you alias  dustbare='dust -c -b -d 1 . | sed "s/[^[:alnum:]+-. ]//g"'
 
 I'm going to close this but I might come back to the bare mode.
