### ISSUE TITLE
flatpak

### ISSUE THREAD

**Issue by mohammadRezaeian** [bootandy/dust#279]
hi thanks for create this software
please publish it for Flatpak.

**Comment by bootandy** [comment]
Todo: Read this and figure this out:
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by bootandy** [comment]
I don't think Flatpack is the right place for a command line tool like dust. I can't find other rust tools like ripgrep, fd or exa on it. 

However, if you want to add dust to Flatpack then I give you permission. Just @ me on the PR and I'll do what I can to help. 

thanks,
