### ISSUE TITLE
Add --reverse flag

### ISSUE THREAD

**Issue by roblav96** [bootandy/dust#28]
## Problem
The results of `dust -s -d=1` in a folder containing many files will be displayed and having to scroll back to the top is, meh.

## Solution
Add a `--reverse` flag so the important information is displayed right at the end of the command execution.

Great work on this friend! 👍

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/commit/4cffc4370b58fb85b7b94e72f67431cced5b3d5d

reverse added
