### ISSUE TITLE
[Feature Request] support show gzip size

### ISSUE THREAD

**Issue by tjx666** [bootandy/dust#281]
It would be very useful for frontend developer to analyze bundle size.

**Comment by bootandy** [comment]
The size of a gzip file is already shown. 

Are you asking for the gzip file to be unzipped and viewed as if it were unzipped?

**Comment by tjx666** [comment]
like this, show the file size of gzip and ungzip

![image](https://user-images.githubusercontent.com/41773861/210690345-cd77e97d-a171-4c5e-b907-572328ebfe46.png)

**Comment by bootandy** [comment]
I think that would be too confusing as some people would want zip files to stay compressed and others would want them to be unpacked. 
So I'm saying no for now. sorry.

**Comment by tjx666** [comment]
What I want to say is：
For front-end developer, the browser usually fetch the assets by gzip format, the gzip size and sort by gzip is usually more helpful because it is closer to reality.
