### ISSUE TITLE
dust is not a supported application

### ISSUE THREAD

**Issue by nick-youngblut** [bootandy/dust#283]
Reprex:

```
curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
deb-get install dust
```

Error:

```
  [!] ERROR! dust is not a supported application.
```

OS: `Ubuntu 20.04.5 `

**Comment by bootandy** [comment]
You are welcome to add dust to deb-get if you want to. 

https://github.com/wimpysworld/deb-get#adding-software

**Comment by nick-youngblut** [comment]
The [README](https://github.com/bootandy/dust) currently states that dust can be installed via `deb-get`:

```bash
deb-get install du-dust
```

Is this not the case?

**Comment by bootandy** [comment]
You can but that version is very old. Let me look at updating it. 

Also I tend to use the name du-dust for packing as dust was taken in crates.io
