### ISSUE TITLE
Empty copyright placeholder in license file

### ISSUE THREAD

**Issue by alexanderkjall** [bootandy/dust#305]
Here: https://github.com/bootandy/dust/blob/master/LICENSE#L189 there is just a placeholder instead of a year and someone's name.

These kind of things might be blockers during package review for inclusion in Debian, could that maybe be filled in?

**Comment by bootandy** [comment]
Good spot, I'll fix it.

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/commit/520c439edcba7fd8e8884e19d98f448553e6a42d
