### ISSUE TITLE
Add musl binary for ARM target

### ISSUE THREAD

**Issue by patrickelectric** [bootandy/dust#311]
ARM only has gnu binaries and that fails depending of the libc version installed, for embedded applications libc versions are more complicated, musl binaries will help with that. 
I would recommend to have musl binaries as default

**Comment by bootandy** [comment]
I tried adding a musl arm target but the build failed:

https://github.com/bootandy/dust/actions/runs/4420050043/jobs/7749252509

any ideas ?

**Comment by patrickelectric** [comment]
> I tried adding a musl arm target but the build failed:
> 
> https://github.com/bootandy/dust/actions/runs/4420050043/jobs/7749252509
> 
> any ideas ?

It appears that you are using strip from host and not for the target.

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/319

Added a musl arm build, it will be included in the next release.

**Comment by patrickelectric** [comment]
Thanks, it works!
