### ISSUE TITLE
Default depth value from config

### ISSUE THREAD

**Issue by yitsushi** [bootandy/dust#314]
The only thing blocks me to alias `dust` to `du` is the `depth` value. I don't want to specify `depth` every single time, and if I forget to add it can be painful if the directory structure is very deep. Most of the time I need `--depth=1`, but not all the time.

I can't set alias to `du="dust --depth=1"` because if I want to use a different value, it will cry about it: "The argument '--depth <depth>' was provided more than once".

The easiest solution would be to add a default value in the config (`depth`) and it would work the same way as other options:
1. If `--depth` is defined, use that value.
2. If `depth` is defined in config, use that value.
3. Otherwise use `usize::MAX` (that's the default now).

Is there a way to achieve it and I just couldn't figure it out or it's a missing feature. If it's a missing feature, I have a branch with it locally so I can file a PR anytime.

**Comment by bootandy** [comment]
this seems reasonable to me.
