### ISSUE TITLE
Optionally exclude files that are excluded from Time Machine backups?

### ISSUE THREAD

**Issue by tko** [bootandy/dust#316]
In addition to seeing how much disk space is used locally it's also useful to see how much is getting backed up, especially if you're in a semi-habit of excluding folders and files (`tmutil addexclusion`) from backups manually.

**Comment by bootandy** [comment]
You can use `dust -X file_or_dir_to_not_count` to ignore certain files or directories. You can also use `dust -v REGEX` to ignore files that match the REGEX

I don't really want to have dust integrate with whatever time machine does as I'd like to keep it separate from other tools.

**Comment by bootandy** [comment]
This request looks similar to https://github.com/bootandy/dust/issues/265 so I'll close this.

**Comment by tko** [comment]
FWIW I believe Time Machine exclusions are recorded as extended attributes on the files so it's little different from separate ignore files.
```
com.apple.metadata:com_apple_backup_excludeItem:
00000000  62 70 6C 69 73 74 30 30 5F 10 11 63 6F 6D 2E 61  |bplist00_..com.a|
00000010  70 70 6C 65 2E 62 61 63 6B 75 70 64 08 00 00 00  |pple.backupd....|
00000020  00 00 00 01 01 00 00 00 00 00 00 00 01 00 00 00  |..........pd....|
00000030  00 00 00 00 00 00 00 00 00 00 00 00 1C           |..........pd....|
0000003D
```
