### ISSUE TITLE
Possibility to have bars to the left?

### ISSUE THREAD

**Issue by BackSpace54** [bootandy/dust#317]
Hi,

is it possible to have bars to the left side?
Like this:
![image](https://user-images.githubusercontent.com/57332400/225094404-55fc3b61-64f5-47ea-a1cd-2b0c652f6e9f.png)

Best regards.

**Comment by bootandy** [comment]
yeah that's possible. Might even make more sense to have them that way round. I'll add it to the todo list.

**Comment by lesleyrs** [comment]
My first thought was to also have the % values on the left as well (next to the sizes).

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/349
