### ISSUE TITLE
`dust` in a deleted/missing directory outputs a different dir

### ISSUE THREAD

**Issue by lesleyrs** [bootandy/dust#326]
I was expecting it to give an error, but instead it shows a completely different directory (in my case it's the default dir, not sure exactly what it's doing). This is on windows.

Thx for this tool btw, helped me clean my ssd as the official windows tools don't show hidden files which is fair I guess.

**Comment by bootandy** [comment]
Are you running dust in the directory after you have deleted the directory ?

**Comment by lesleyrs** [comment]
Yes, by deleting it in file explorer instead of the terminal. I think this causes it to output the default starting directory, I'd prefer just an error message.

**Comment by bootandy** [comment]
I'm not sure that's going to be possible. 

what happens if you run dust on a directory that doesn't exist in windows:

dust C:\THIS_DOES_NOT_EXIST/\

?

**Comment by lesleyrs** [comment]
If it's not going to work feel free to close, it's not a big deal but would just be a little improvement.

It shows
>Did not have permissions for all directories
