### ISSUE TITLE
The PATH set by the winget package and the binary location don't match

### ISSUE THREAD

**Issue by cafce25** [bootandy/dust#328]
The [winget package for dust](https://github.com/microsoft/winget-pkgs/tree/2db6d25249f5b97a9d963d4ef810889ee99d7de6/manifests/b/bootandy/dust) installs the binary into `%LocalAppData%\Microsoft\WinGet\Packages\bootandy.dust_Microsoft.Winget.Source_8wekyb3d8bbwe\dust-v0.8.6-x86_64-pc-windows-gnu` which is fine, but it then proceeds to add only `%LocalAppData%\Microsoft\WinGet\Packages\bootandy.dust_Microsoft.Winget.Source_8wekyb3d8bbwe` to the `$PATH` so after installation and restarting the shell, `dust` is not available on the command line.

One possible resolution to this would be to have the executable directly in the zip file, without the sub directory, which is why I bring this up here. Other solutions might be to change the actual `winget` package, but I don't know if that's even possible.

I'm not entirely sure this Issue shouldn't be on the `winget-pkgs` repository instead, but since `winget` is listed on the list of package managers it might as well be here, let me know if I should open it there instead.

**Comment by bootandy** [comment]
I think that will be an issue with `winget-pkgs`, please open the issue with them . Thanks.
