### ISSUE TITLE
Allow options to be used multiple times.

### ISSUE THREAD

**Issue by pcroland** [bootandy/dust#330]
This would improve flexibility with aliases. For example i have `alias dust="dust -r"` in my `.zshrc`, so now if i run `dust -r`, it throws an error:
`error: The argument '--reverse' was provided more than once, but cannot be used multiple times`

**Comment by bootandy** [comment]
That sounds reasonable, although this might be down to the library I am using to parse command line options.

**Comment by johntheocs** [comment]
Maybe we can remove the duplicated options before passing them down to the library.

**Comment by bootandy** [comment]
If I can remove duplicate options then I'm parsing the input. Then there is no point in the library as I've already parsed the input. 

there might be a flag in the library I can set somewhere.
