### ISSUE TITLE
Could you add an option to only display total?

### ISSUE THREAD

**Issue by ModProg** [bootandy/dust#334]
I'm basically looking for a shorthand for `--number-of-lines 0`

**Comment by ModProg** [comment]
yes I knew about `-n0` I was just wondering if it made sense to have an actual option for that. but maybe not, `-n0` is already pretty short. And `--only-total` is only slightly more self explaining than `--number-of-lines=0`

**Comment by cppxor2arr** [comment]
> yes I knew about -n0 I was just wondering if it made sense to have an actual option for that.

Oh, I see what you mean. To me, a depth of 0 is pretty close to meaning "only display the total".

**Comment by ModProg** [comment]
In my case only `-n0` worked, because I was piping in filenames to measure the total size of all images on my disk.

**Comment by bootandy** [comment]
thanks to @cppxor2arr I'll close this.
