### ISSUE TITLE
dust run by root crash the Mac M1 at root folder /

### ISSUE THREAD

**Issue by 9to1url** [bootandy/dust#336]
I have a Mac M1 machine.
I sudo -i to root
cd /
dust 

Started to hear the fan very loud and run for around 20 seconds, the machine get rebooted.

Please advise what happen.
I have the problem report after login in machine again, let me know if need that.

**Comment by bootandy** [comment]
Sounds like your computer over-heated. Can you make your Mac use less cpu ?

**Comment by 9to1url** [comment]
My computer barely use any CPU until I triggered the dust 😃

**Comment by bootandy** [comment]
dust will use a lot of CPU when it runs
