### ISSUE TITLE
Not print full paths of files

### ISSUE THREAD

**Issue by SplitGemini** [bootandy/dust#339]
I use command `dust -F -n 100000000000 -P -c -r -p -s -d 1000 -b . >size.txt`
but paths in my size.txt were cut by `..` at last as below:
![image](https://github.com/bootandy/dust/assets/34861918/e7bb1f1f-9190-46b2-ace8-f613e83d6de3)

how can I get full paths to collect?

**Comment by bootandy** [comment]
Tell it your terminal is really wide with the '-w' flag:

`$ dust -F -n 100000000000 -P -c -r -p -s -d 1000 -b -w 9999 . > size          `
