### ISSUE TITLE
build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by horse-latitudes** [bootandy/dust#34]
cargo bails out whilst compiling:

`error[E0432]: unresolved import `self::std::hint`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:13:16
   |
13 | use self::std::hint::unreachable_unchecked;
   |                ^^^^ Could not find `hint` in `std`

error: aborting due to previous error

error: Could not compile `lazy_static`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `du-dust v0.4.0`, intermediate artifacts can be found at `/tmp/cargo-install.9fTx6Q9xf9f3`

Caused by:
  build failed
`
any help appreciated,

Phil.

**Comment by horse-latitudes** [comment]
I ran `rustup` & upgraded both rust and cargo to 1.38.0 & running build again succeeded.

Sorry for the noise.

**Comment by bootandy** [comment]
no worries, glad you got it fixed.
