### ISSUE TITLE
By default, disable progress indicator if stdout is redirected to a file

### ISSUE THREAD

**Issue by jjvliu** [bootandy/dust#342]
When running a command like `dust > dust.log`, the output file will begin with an extremely long line that contains every copy of the progress indicator and control characters for erasing the terminal, such as

    ^M ^MIndexing: /path/to/dir 6894 files, 5.3G ... -^M                                                              ^MIndexing: /path/to/dir 14345 files, 268G ... \

A simple fix for this would be to enable the `-P` or `--no-progress` flag by default if `dust` detects that stdout was redirected to a file, for example using `!isatty` from libc.

**Comment by bootandy** [comment]
good idea.

**Comment by bootandy** [comment]
Fixed on head.
