### ISSUE TITLE
.deb for aarch64

### ISSUE THREAD

**Issue by Cysioland** [bootandy/dust#344]
It'd be nice to have aarch64 debs available on the "Releases" page or in deb-get in addition to i386/amd64 debs

**Comment by bootandy** [comment]
I confess to having very little understanding of how cargo works for building releases, If you know what bits to poke on the CICD.yml file - please be my guest.

**Comment by Cysioland** [comment]
Had a lazy stab at it and it did not work (it seems like you've tried the same things as me). Maybe I'll try finding time to delve deeper into this.

**Comment by bootandy** [comment]
No idea, can't figure this out. Will happily accept a PR from whoever figures this out.
