### ISSUE TITLE
Feature request: disk on all local disks

### ISSUE THREAD

**Issue by stepancheg** [bootandy/dust#346]
There can be multiple local disks (or partitions of the disk like APFS volumes).

Would be convenient if dust had a flag like `dust --all-local-disks` to get output combined from all of them.

Currently the second best option is something like

```
mount | grep /dev/disk | grep apfs | awk '{ print $3 }' | sudo xargs dust -x
```

**Comment by bootandy** [comment]
it's an interesting idea. I'm not sure how I would detect which file-systems should be included in 'all-local-disks' though.

**Comment by stepancheg** [comment]
I'm not sure how it can be done cross-platform. Perhaps some per-OS logic can be implemented. For macOS it can be this.

For macOS I guess the algorithm is this:
* run `diskutil list` to find all real disks (excluding images) and partitions on them
* then `mount` to find the mount roots for these local disks

For Linux it might be more complicated because ecosystem is much larger.

**Comment by bootandy** [comment]
I'm going to close this I'm not sure how I can do this.

**Comment by stepancheg** [comment]
Not sure can be done universally, but for macos I have shown the command.

Anyway, thank you for the great tool!
