### ISSUE TITLE
Performance is affected by battery status

### ISSUE THREAD

**Issue by Feel-ix-343** [bootandy/dust#365]
I am not sure if this is dust or linux specific, but I have noticed that Dust is significantly slower when my laptop's battery is not charging. 

I am labeling this as an issue, as it is unexpected behavior for me. 

Is this a dust feature? or a linux thing? And can it be changed or configured in settings?

**Comment by bootandy** [comment]
It'll be a linux thing, When your battery is charging the OS will allow the CPU to run faster. This will effect all cpu-intensive applications.
