### ISSUE TITLE
Optiong to not color output

### ISSUE THREAD

**Issue by kbknapp** [bootandy/dust#37]
It'd be great if there was an option to *not* color the output, or if automatically detected that the output was not a TTY and skipped coloring automatically. This would help when using `dust | less` or with things like `watch`.

**Comment by bootandy** [comment]
I'll have a look at this soon

**Comment by bootandy** [comment]
`watch -c | dust`
will work too. Although I would still like to add a no color version.

**Comment by bootandy** [comment]
can now do this by running  `dust -c` on version 0.4.2
