### ISSUE TITLE
Add pager?

### ISSUE THREAD

**Issue by leodking** [bootandy/dust#379]
It's a bit strange that dust seems to limit the output to whatever can fit on the terminal, without even printing the rest. So I can only see the subtotal sizes for a subset of directories in the directory I want to analyse.

Is there any way to get the output onto a pager, or to simply print it, however long it is?

**Comment by bootandy** [comment]
It's not meant to output everything - that's what du is for. 

If you want to replicate that behaviour I recommend using the '-d' flag. so `dust -d 9` - it will go 9 levels deep I doubt you'd want more, but if you do just increase the number.
