### ISSUE TITLE
Dust tree by age

### ISSUE THREAD

**Issue by bootandy** [bootandy/dust#385]
Instead of showing file size. Show the time of the most recently updated file in the subdirectory. 

Also a flag for oldest

Normally stat will show the time the directory was last touched - this version will show the max/min time of it and all it's contents.

**Comment by l-armstrong** [comment]
Hello, I'm new to the project. I wanted to know if this issue is till open to being worked on?

**Comment by wugeer** [comment]
Hello, is the following output OK? I will submit a PR if I can![image](https://github.com/bootandy/dust/assets/20339490/442e1584-ff9f-4042-bb8f-a82c4df0ee8c)

**Comment by bootandy** [comment]
Yeah, that works - do you think we should have '-' between the year-month-day columns to make it more readable (trading losing somre screen real estate)

**Comment by wugeer** [comment]
> Yeah, that works - do you think we should have '-' between the year-month-day columns to make it more readable (trading losing somre screen real estate) Add a "-" between the year, month and day columns to make it easier to read (losing some screen space in the deal)?

Yeah, originally  I think the readability isn't significantly affected by the presence or absence of the hyphen, but it saves screen space, so I removed it in the initial version. 
I have resubmitted the code, and the performance test screenshots have also been submitted. Please check if there are any issues and if more performance test examples are needed.
