### ISSUE TITLE
`--only-file` displays full paths even without `--full-paths`

### ISSUE THREAD

**Issue by eatsu** [bootandy/dust#386]
First of all, thank you very much for this helpful tool.

I have an issue that `--only-file` displays full paths even without `--full-paths`, like this:

```console
$ dust --only-file /path/to/target-dir
...   ┌── /path/to/target-dir/foo         ...
...   ├── /path/to/target-dir/sub-dir/bar ...
... ┌─┴ /path/to/target-dir               ...
```

It would be nice if it could display the shortened, relative paths by default, like this:

```console
$ dust --only-file /path/to/target-dir
...   ┌── foo         ...
...   ├── sub-dir/bar ...
... ┌─┴ target-dir    ...
```

I'm using Dust 1.0.0 on Arch Linux.

**Comment by bootandy** [comment]
That's a good point, I'll look into this.
