### ISSUE TITLE
Parallelisation seems excessive

### ISSUE THREAD

**Issue by Debilski** [bootandy/dust#387]
I ran dust on a server with >40 cores and htop was basically going all red from system call CPU usage. Is it possible to have a lower default on the number of threads that dust uses per default? I have my doubts that it makes much of a difference after a certain threshold.

I am aware that I can set `RAYON_NUM_THREADS=1` on the command line but since this is a shared system the majority of users won’t know about this setting.

**Comment by Dj-Codeman** [comment]
I agree that a way to limit threads better than `Rayon_whatever` is needed but I think the default behavior is okay. Going back and forth from my Hpe server with Tb's of data and my laptop tweaking the default thread pool would hinder at least one of those use cases. I suggest  #388, it just adds a `-T` flag to allow us to specify however many threads we want.

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/395
will go out in next release. thanks @Dj-Codeman
