### ISSUE TITLE
`kib`, `mib`, etc for `-o` should be powers of 1024, not 1000

### ISSUE THREAD

**Issue by eatsu** [bootandy/dust#391]
According to [Wikipedia](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units), KiB, MiB, etc are units based on [binary prefixes](https://en.wikipedia.org/wiki/Binary_prefixes) which are powers of 1024, but in Dust they seem to be treated as [SI units](https://en.wikipedia.org/wiki/SI_prefix) which are powers of 1000.

https://github.com/bootandy/dust/blob/v1.0.0/src/display.rs#L412-L420

I'm afraid this is technically incorrect and is confusing.

For reference, commands `du`, `df` and `ls` treat `K`, `M`, `KiB`, `MiB`, etc as powers of 1024 and `KB`, `MB`, etc as powers of 1000. Quoting from their `--help`:

```
The SIZE argument is an integer and optional unit (example: 10K is 10*1024).
Units are K,M,G,T,P,E,Z,Y,R,Q (powers of 1024) or KB,MB,... (powers of 1000).
Binary prefixes can be used, too: KiB=K, MiB=M, and so on.
```

I would appreciate it if this were fixed and `k`, `m`, etc could be used as aliases for `kib`, `mib`, etc, like the above commands convention.

Thanks!

**Comment by bootandy** [comment]
Oh wow that's embarrassing. I've implemented it backwards, haven't I. Good find. How did you notice that ? 

I think this is a recent bug only in this version, it's from when I merged the behaviour of the now redundant `--si` flag.

**Comment by bootandy** [comment]
https://github.com/bootandy/dust/pull/392

does this look right ?

**Comment by eatsu** [comment]
> How did you notice that ?

I noticed that the values of the output K was different between with `-o kib` and without the flag when working on `_dust_output_formats` in #390 :)

> does this look right ?

`kib` / `mib` / `kb` / `mb` work now as I expected as far as I've tested. Thank you! However, it seems that `k` / `m` are now powers of 1000, which is different from the behavior of `du` / `df` / `ls`.

**Comment by bootandy** [comment]
Noted, updated.

**Comment by eatsu** [comment]
Ah, it now works perfectly for me. Thank you again!

**Comment by bootandy** [comment]
will go out in next release
