### ISSUE TITLE
Panic when running dust

### ISSUE THREAD

**Issue by maanaskarwa** [bootandy/dust#409]
just installed rust on a server and ran cargo install du-dust. This is the output when running dust:

thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:168:10:
The global thread pool has not been initialized.: ThreadPoolBuildError { kind: GlobalPoolAlreadyInitialized }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

System Info:
LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

stack backtrace:
   0:     0x55839c439462 - <unknown>
   1:     0x55839c36aabb - <unknown>
   2:     0x55839c410f32 - <unknown>
   3:     0x55839c43e739 - <unknown>
   4:     0x55839c43df5e - <unknown>
   5:     0x55839c43f184 - <unknown>
   6:     0x55839c43eaa2 - <unknown>
   7:     0x55839c43e9f9 - <unknown>
   8:     0x55839c43e9e6 - <unknown>
   9:     0x55839c2b39c2 - <unknown>
  10:     0x55839c2b3dd5 - <unknown>
  11:     0x55839c383a4a - <unknown>
  12:     0x55839c2e59b3 - <unknown>
  13:     0x55839c2c1da3 - <unknown>
  14:     0x55839c2f5a80 - <unknown>
  15:     0x55839c2c8803 - <unknown>
  16:     0x55839c2fe591 - <unknown>
Indexing: . 0 files, 0B ... -  17:     0x7fd0d4f72d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  18:     0x7fd0d4f72e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  19:     0x55839c2c05b5 - <unknown>
  20:                0x0 - <unknown>

**Comment by bootandy** [comment]
Was this a 32 bit server ? 


https://github.com/bootandy/dust/blob/master/src/main.rs#L357

**Comment by bootandy** [comment]
maybe try this:
export RAYON_NUM_THREADS=1 

https://github.com/bootandy/dust/issues/296

Although we need to fix what is causing this.

**Comment by maanaskarwa** [comment]
The export command fixed it. This is a 64-bit server (getting x86_64 when running arch)
