### ISSUE TITLE
Incorrect position of folder where prefix is identical to filename

### ISSUE THREAD

**Issue by b-hahn** [bootandy/dust#41]
Thanks for the nice work on dust!

I ran into an issue on Ubuntu 18.04 where I have a folder called folder.bag.map and a file called file.bag. The resulting dust output when run in the parent folder is:
```bash
user:~/developer/$ dust
  62G ─┬ .
  19G  ├─┬ file.bag
 179M  │ └─┬ folder.bag.map
 119M  │   ├─┬ subfolder1
 119M  │   | └── file1.txt
  59M  │   └─┬ subfolder2
  38M  │     └── file2.txt

```

i.e. it seems like the file file.bag is treated like a folder and folder.bag.map is treated as a subfolder of the file. Maybe there's a parsing issue here somewhere?

**Comment by bootandy** [comment]
Hi,

If you mean the file is called 'folder.bag' so it is a substring of the folder name 'folder.bag.map' then I can reproduce this. 

```
$ target/debug/dust ~/tmp                                                                                                        [21:01:24]
  16K ─┬ tmp
 4.0K  ├── file.bag
 4.0K  └─┬ folder.bag
 4.0K       └─┬ folder.bag.mat
   0B             └── hello
```

I can not reproduce this with a file called 'file.bag' at the same level as a folder called 'folder.bag.map' 

Can I ask which version of dust you are running (dust --version) - If there is no output it is old as it is pre 0.4.

**Comment by bootandy** [comment]
I thought this was fixed with:
https://github.com/bootandy/dust/commit/6e03dd77e61d7a479e653dc5e5031372f05fe0c8
but I was clearly wrong

**Comment by bootandy** [comment]
I think this commit reintroduced this bug : db6c8a0
