### ISSUE TITLE
Lock file for v1.1.0 not up to date

### ISSUE THREAD

**Issue by alerque** [bootandy/dust#418]
I'm trying to update distro packages (Arch Linux) which build with `--frozen` and the lock file for the release is not up to date with the manifest, so it won't build. Please make sure to update the lock file in conjunction with releases so they can be built in a reproducible manner. Thanks.

**Comment by alerque** [comment]
The culprit seems to be having bumped the version of *this* crate in Cargo.toml but not run `cargo build` to update the lock file to match. When cutting releases it is important to update both places!

**Comment by bootandy** [comment]
Sorry my bad. I have a performance bug to fix in v1.1.0 so I'll release v1.1.1 shortly.

**Comment by bootandy** [comment]
pushing a new version now 

Updated release notes - so hopefully won't make this mistake again:
https://github.com/bootandy/dust/commit/dbd18f90e7b184d12f14533e76e5915dbe4a2051
