### ISSUE TITLE
Adding a new installation method to the README

### ISSUE THREAD

**Issue by lunrenyi** [bootandy/dust#434]
- Hi, we have implemented a lightweight [package manager using shell and awk](https://www.x-cmd.com/pkg/). 
It helps you download dust release packages from the internet and extract them into a unified directory for management, without requiring root permissions.

- **I mean, can the installation method provided by x-cmd be added to the dust README?**
  ```sh
  # eval "$(curl https://get.x-cmd.com)"    # Install the x command
  x env use dust
  ```
- [dust demo](https://www.x-cmd.com/pkg/dust): x-cmd recorded a demo and article for dust

Looking forward to your reply :) !

**Comment by bootandy** [comment]
Certainly, I'll include that now
