### ISSUE TITLE
The total size of my Mac's hard disk is only 1T, but the results of the dust execution have far exceeded this size

### ISSUE THREAD

**Issue by persiliao** [bootandy/dust#437]
![WX20240903-123418](https://github.com/user-attachments/assets/e4ba07ef-19d2-418b-a2ec-a5b261cd4274)

**Comment by bootandy** [comment]
Could be rounding. What did the output look like when dust finished ?

**Comment by persiliao** [comment]
@bootandy The final result displayed is correct
