### ISSUE TITLE
Add an option to skip directories on other filesystems

### ISSUE THREAD

**Issue by kpine** [bootandy/dust#50]
Consider adding an `-x` option, which is available in both `du` and `ncdu`. The option would exclude any directories that reside on other filesystems. This is useful when you want to find what directories are taking all the space on a particular filesystem, but have network or other disks mounted in other directories.

For example, `ncdu -x` from the root directory will show this on my system:
```
ncdu 1.13 ~ Use the arrow keys to navigate, press ? for help
--- / ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   38.2 GiB [##########] /var
   35.4 GiB [######### ] /home
    4.4 GiB [#         ] /nix
    4.4 GiB [#         ] /usr
...
    4.0 KiB [          ] /mnt
...
```
With dust it shows:
```
$ dust -d1
 277G ─┬ .
 192G  ├── mnt
  40G  ├── var
  35G  ├── home
 4.4G  ├── nix
 4.4G  ├── usr
...
```
`/mnt` has a CIFS shared mounted from a NAS, so it throws off the totals.

#46 is related, but would be less convenient to use if there were other filesystems mounted in various locations.

**Comment by bootandy** [comment]
good suggestion, I'll add it to the todo list and should probably do #46 at the same time.
