### ISSUE TITLE
Suggestion: stick to semantic versioning

### ISSUE THREAD

**Issue by jc21** [bootandy/dust#68]
Looking through your release history, your versioning scheme is all over the place.

I'm packaging your software on my [Centos](https://yum.jc21.com) and [Debian](https://dpkg.jc21.com) repositories and it's easier for me if the version is of a consistent standard, `v0.0.0`. In these package managers, `v4` is newer than your latest release of `v0.4.5.0`. I would argue that you don't need 4 levels of version numbers either.

Just a suggestion to make things easier for the consumers of your software :)

**Comment by bootandy** [comment]
Hi,

v4 was an accident its version is v0.4.0 and it was marked as a pre-release because of this. 

Mostly these things occur as an accident and I can't see how to delete them from github.

Should I drop the 'v' from the versioning? Is that annoying?

**Comment by jc21** [comment]
With or without the v is fine and doesn’t matter. It was just a matter of semantic versioning.
