### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by NotAFile** [bootandy/dust#7]
I'm mostly writing this so I get the close notification when this happens, but it would be neat if there were rpm/deb packages for dust.

**Comment by rushmorem** [comment]
In the mean time you can easily install this using `cargo`:-

```bash
cargo install --git https://github.com/bootandy/dust
```

**Comment by pickfire** [comment]
Maybe https://github.com/rust-lang-nursery/cli-wg/issues/8 would be sufficient to be tracked?

**Comment by jab** [comment]
https://docs.brew.sh/Formula-Cookbook in case it's helpful to anyone wants to package this for Homebrew!

**Comment by dawidd6** [comment]
It's already available in Homebrew: https://github.com/Homebrew/homebrew-core/blob/master/Formula/dust.rb

**Comment by bootandy** [comment]
I found this: 
https://mirror1.centos-org.ru/packages/dust/

I guess it has been packaged by now.

**Comment by kurczynski** [comment]
> I found this:
> https://mirror1.centos-org.ru/packages/dust/
> 
> I guess it has been packaged by now.

This link seems to be dead now. Can this be reopened?
