### ISSUE TITLE
Option to emulate tree's behavior

### ISSUE THREAD

**Issue by kiwijam** [bootandy/dust#88]
It would be nice to have an options shortcut (--tree?) that makes dust behave more like tree, by that I mean:

- Unsorted (alphabetically sorted?) output
- No line-limit
- No bars
- Optionally: --no-filesizes

**Comment by bootandy** [comment]
* No, I don't want to do (1), dust should always sort by size
* `dust -d 99 ` in practise gives you no line limit. If you want true no line limit I think using 'du' would be better.
* `dust -b` gives no bars 
* I can't think why anyone would not want file sizes on the output as I think this is the main usage of dust is to show file sizes.

Thank you for your suggestion but I will decline.
