### ISSUE TITLE
Output is padded even when bars are turned off

### ISSUE THREAD

**Issue by kiwijam** [bootandy/dust#89]
Output is always padded with spaces to the longest filename even when bars are turned off - makes it a bit harder to use dust's output in other programs.

![image](https://user-images.githubusercontent.com/7322709/81218570-af03e080-8fde-11ea-89c7-4b533cbb6f5d.png)

**Comment by bootandy** [comment]
True, you raise an interesting edgecase there. I'll look into fixing that.

**Comment by bootandy** [comment]
shipped in 0.5.2
