### ISSUE TITLE
Low memory

### ISSUE THREAD

**Issue by anisse** [bootandy/dust#91]
I had dust fail when it ran out of memory:
```
memory allocation of 26214400 bytes failedAbandon
```

GNU sort uses temporary files so that it offloads big allocations to disk. Could this be considered ?

**Comment by bootandy** [comment]
Seems reasonable to me, 

I did a bit of a re-write recently that may mitigate this.

**Comment by bootandy** [comment]
I use walkdir now as of  0.5.2 so this is probably fixed.
