### ISSUE TITLE
Incorrect calculation in apparent size

### ISSUE THREAD

**Issue by travankor** [bootandy/dust#94]
`dust -s` seems to have contradicting output compared to `du --apparent-size`. Apparent size should usually be less than block size.

I ran `dust -sn0 /gnu` on the guix package store and have 21G, while `du --apparent-size -sh /gnu` returns 8.4G. I think dust counts hardlinks twice (since guix uses hardlinks to save space) although I'm not sure.

**Comment by bootandy** [comment]
`dust -s` counts hardlinks as taking up space on disk. 

`du --apparent-size` does not count hardlinks as taking up space on disk

Intuitively I 'feel' like I did the right thing with dust and du does the wrong thing. But this is open to debate.
